/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedPostsIndexRouteImport } from './routes/(authenticated)/posts/index'
import { Route as unauthenticatedauthLoginRouteImport } from './routes/(unauthenticated)/(auth)/login'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedPostsIndexRoute = authenticatedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const unauthenticatedauthLoginRoute =
  unauthenticatedauthLoginRouteImport.update({
    id: '/(unauthenticated)/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/login': typeof unauthenticatedauthLoginRoute
  '/posts/': typeof authenticatedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedIndexRoute
  '/login': typeof unauthenticatedauthLoginRoute
  '/posts': typeof authenticatedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(unauthenticated)/(auth)/login': typeof unauthenticatedauthLoginRoute
  '/(authenticated)/posts/': typeof authenticatedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/posts'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/'
    | '/(unauthenticated)/(auth)/login'
    | '/(authenticated)/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  unauthenticatedauthLoginRoute: typeof unauthenticatedauthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/posts/': {
      id: '/(authenticated)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof authenticatedPostsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(unauthenticated)/(auth)/login': {
      id: '/(unauthenticated)/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedPostsIndexRoute: typeof authenticatedPostsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedPostsIndexRoute: authenticatedPostsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  unauthenticatedauthLoginRoute: unauthenticatedauthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
