/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'

const authenticatedIndexLazyRouteImport = createFileRoute('/(authenticated)/')()
const authenticatedPostsIndexLazyRouteImport = createFileRoute(
  '/(authenticated)/posts/',
)()
const unauthenticatedauthLoginLazyRouteImport = createFileRoute(
  '/(unauthenticated)/(auth)/login',
)()

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexLazyRoute = authenticatedIndexLazyRouteImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(authenticated)/index.lazy').then((d) => d.Route),
  )
const authenticatedPostsIndexLazyRoute = authenticatedPostsIndexLazyRouteImport
  .update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(authenticated)/posts/index.lazy').then((d) => d.Route),
  )
const unauthenticatedauthLoginLazyRoute =
  unauthenticatedauthLoginLazyRouteImport
    .update({
      id: '/(unauthenticated)/(auth)/login',
      path: '/login',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(unauthenticated)/(auth)/login.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexLazyRoute
  '/login': typeof unauthenticatedauthLoginLazyRoute
  '/posts/': typeof authenticatedPostsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedIndexLazyRoute
  '/login': typeof unauthenticatedauthLoginLazyRoute
  '/posts': typeof authenticatedPostsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/': typeof authenticatedIndexLazyRoute
  '/(unauthenticated)/(auth)/login': typeof unauthenticatedauthLoginLazyRoute
  '/(authenticated)/posts/': typeof authenticatedPostsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/posts'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(authenticated)/'
    | '/(unauthenticated)/(auth)/login'
    | '/(authenticated)/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  unauthenticatedauthLoginLazyRoute: typeof unauthenticatedauthLoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexLazyRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/posts/': {
      id: '/(authenticated)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof authenticatedPostsIndexLazyRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(unauthenticated)/(auth)/login': {
      id: '/(unauthenticated)/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedauthLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexLazyRoute: typeof authenticatedIndexLazyRoute
  authenticatedPostsIndexLazyRoute: typeof authenticatedPostsIndexLazyRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexLazyRoute: authenticatedIndexLazyRoute,
  authenticatedPostsIndexLazyRoute: authenticatedPostsIndexLazyRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  unauthenticatedauthLoginLazyRoute: unauthenticatedauthLoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
